import { Header } from '@books/components/src/header/header'
import { SuperTokensProvider } from "../components/supertokensProvider";
import './globals.css'

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* @ts-expect-error becasuse I said so*/}
        <SuperTokensProvider>
          <Header />
          <main className="container mx-auto px-4 py-8 max-w-3xl">
            {children}
          </main>
        </SuperTokensProvider>
      </body>
    </html>
  );
}
